

// function getPositives(arr) {
//   const posArr = arr.filter((num) => num > -1);
//   return posArr;
// }
// console.log(getPositives([1, -2 - 3, -4]));

 
// let array = [1, 2, -3, 4, 5, -6, -7, 10, 17, 22];
// const getPositiveNumbers = (arr) => {
//   for()
// }
  

let list = ['l', 10, 'd', 8, 11, 'n', 20, 9, 'y', 35];
const returnNumbers = (list) => {
  let Numbers = [];
  for (let i of list) {
    if (i == '') {
      Numbers.push(i);
    }
  }
  return Numbers;
};
return Numbers(list);

console.log(indexOf(i))

// function removeLetters(list) {
//   const returnNumbers = (list) => {
//     let numbers = [];
//     for (let i of list) {
//       if (isNan == '') {
//         numbers.push(i)

//       }
//     }
//     returnNumbers;
//   };
//   returnNumbers(list);
// }
// console.log(removeLetters(list(1, u, l, 0, v, 3, y, 0, u))

