const solution = (str) => str.split("").reverse().join("");

// const pureFunction = (a) => {
//   return a * 2;
// };

// const numberToMultply = 4;

// const notPureFunction = (a) => {
//   return a * numberToMultply;
// };

// // console.log("pure", pureFunction(2));
// // console.log("not", notPureFunction(2));

// function negative(num){
//     const negative + num;
// }
// return answer;

// const negative = (num) => {
//     let new = num - num
//     if (num < 0);
//     return num;
//     else {
//     new - num;
//     }
// return new;
// }
function sayHello(name) {
  console.log("Hello, " + name);

  return "Hello, " + name;
}
sayHello('kamva');